version: '3'
services:   
  mysql:
    image: mysql:${IMAGE_TAG}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: myapp-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    ports: 
      - "30002:3306"

  web:
    build: .
    ports:
     - "30001:5000"
  
  redis:
    image: "redis:alpine"